### ISSUE TITLE
notifier dead locks on os x

### ISSUE THREAD

**Issue by whodevil** [jhegg/github-desktop-notifier#16]
The notifier dead locks when the user unchecked the "display tray icon" in the preferences.

``` java
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.20-b23 mixed mode):

"AWT-EventQueue-0" #29 prio=6 os_prio=31 tid=0x00007feed9308800 nid=0x8f1b runnable [0x000000012b154000]
   java.lang.Thread.State: RUNNABLE
        at sun.lwawt.macosx.CInputMethod.getNativeLocale(Native Method)
        at sun.lwawt.macosx.LWCToolkit.getDefaultKeyboardLocale(LWCToolkit.java:711)
        at sun.awt.im.ExecutableInputMethodManager.getDefaultKeyboardLocale(ExecutableInputMethodManager.java:419)
        at sun.awt.im.InputContext.<init>(InputContext.java:131)
        at sun.awt.im.InputMethodContext.<init>(InputMethodContext.java:88)
        at java.awt.im.InputContext.getInstance(InputContext.java:92)
        at java.awt.Window.getInputContext(Window.java:1426)
        - locked <0x00000006c0df8c98> (a java.lang.Object)
        at java.awt.Component.removeNotify(Component.java:7008)
        - locked <0x00000006c104c9f0> (a java.awt.Component$AWTTreeLock)
        at java.awt.Container.removeNotify(Container.java:2820)
        - locked <0x00000006c104c9f0> (a java.awt.Component$AWTTreeLock)
        at java.awt.Window.removeNotify(Window.java:782)
        - locked <0x00000006c104c9f0> (a java.awt.Component$AWTTreeLock)
        at java.awt.Frame.removeNotify(Frame.java:1041)
        - locked <0x00000006c104c9f0> (a java.awt.Component$AWTTreeLock)
        at java.awt.Window$1DisposeAction.run(Window.java:1194)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
        at java.awt.EventQueue.access$400(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:697)
        at java.awt.EventQueue$3.run(EventQueue.java:691)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:719)
        at java.awt.EventQueue$4.run(EventQueue.java:717)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
       a.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

"AWT-Shutdown" #23 prio=5 os_prio=31 tid=0x00007feedb755800 nid=0xf61b in Object.wait() [0x000000012f3a4000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at sun.awt.AWTAutoShutdown.run(AWTAutoShutdown.java:295)
        - locked <0x00000006c1371db0> (a java.lang.Object)
        at java.lang.Thread.run(Thread.java:745)

"Java2D Queue Flusher" #22 daemon prio=10 os_prio=31 tid=0x00007feedb6b3800 nid=0xf217 in Object.wait() [0x000000012e116000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at sun.java2d.opengl.OGLRenderQueue$QueueFlusher.run(OGLRenderQueue.java:203)
        - locked <0x00000006c0df87b8> (a sun.java2d.opengl.OGLRenderQueue$QueueFlusher)

"Java2D Disposer" #21 daemon prio=10 os_prio=31 tid=0x00007feedb726000 nid=0xf313 in Object.wait() [0x000000012da33000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:142)
        - locked <0x00000006c13f6a08> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:158)
        at sun.java2d.Disposer.run(Disposer.java:148)
        at java.lang.Thread.run(Thread.java:745)

"ScheduledService Delay Timer" #18 daemon prio=5 os_prio=31 tid=0x00007feeda1eb800 nid=0xdd03 in Object.wait() [0x000000012991b000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at java.util.read.mainLoop(Timer.java:526)
        - locked <0x00000006c02551e8> (a java.util.TaskQueue)
        at java.util.TimerThread.run(Timer.java:505)

"Prism Font Disposer" #17 daemon prio=10 os_prio=31 tid=0x00007feedba24000 nid=0xdc0b in Object.wait() [0x0000000129e3f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:142)
        - locked <0x00000006c025cf80> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:158)
        at com.sun.javafx.font.Disposer.run(Disposer.java:93)
        at java.lang.Thread.run(Thread.java:745)

"JavaFX-Launcher" #16 prio=5 os_prio=31 tid=0x00007feedb32d800 nid=0xdb0f waiting on condition [0x00000001295dc000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000006c0696788> (a java.util.concurrent.CountDownLatch$Sync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:831)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$147(LauncherImpl.java:157)
        at com.sun.javafx.application.LauncherImpl$$Lambda$49/868737467.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:745)

"Thread-3" #14 daemon prio=5 os_prio=31 tid=0x00007feedd1f0800 nid=0x980b runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"JavaFX Application Thread" #13 prio=5 os_prio=31 tid=0x00007feed9067800 nid=0x713 in Object.wait() [0x00007fff5beec000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at java.awt.EventQueue.invokeAndWait(EventQueue.java:1301)
        - locked <0x000000076d450348> (a java.awt.EventQueue$1AWTInvocationLock)
        at java.awt.Window.doDispose(Window.java:1214)
        at java.awt.Window.dispose(Window.java:1151)
        at sun.lwawt.macosx.CTrayIcon.dispose(CTrayIcon.java:140)
        at java.awt.TrayIcon.removeNotify(TrayIcon.java:707)
        at java.awt.SystemTray.remove(SystemTray.java:312)
        - locked <0x00000006c0dfaf58> (a java.awt.SystemTray)
        at java_awt_SystemTray$remove$2.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at com.jhegg.github.notifier.App$_removeAppFromTray_closure7.doCall(App.groovy:210)
        at com.jhegg.github.notifier.App$_removeAppFromTray_closure7.doCall(App.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at groovy.lang.Closure.call(Closure.java:423)
        at groovy.lang.Closure.call(Closure.java:417)
        at groovy.lang.Closure.run(Closure.java:504)
        at com.sun.javafx.application.PlatformImpl.lambda$null$164(PlatformImpl.java:292)
        at com.sun.javafx.application.PlatformImpl$$Lambda$48/2109472277.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.applicattformImpl.lambda$runLater$165(PlatformImpl.java:291)
        at com.sun.javafx.application.PlatformImpl$$Lambda$47/1768305536.run(Unknown Source)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

"Thread-1" #12 daemon prio=5 os_prio=31 tid=0x00007feed9014000 nid=0x6513 in Object.wait() [0x0000000124443000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at com.sun.glass.ui.InvokeLaterDispatcher.run(InvokeLaterDispatcher.java:126)
        - locked <0x00000006c0261900> (a java.lang.StringBuilder)

"QuantumRenderer-0" #10 daemon prio=5 os_prio=31 tid=0x00007feedd09d800 nid=0x5103 waiting on condition [0x0000000123bf4000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000006c0262220> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        at java.lang.Thread.run(Thread.java:745)

"Service Thread" #9 daemon prio=9 os_prio=31 tid=0x00007feedb053800 nid=0x4d03 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread3" #8 daemon prio=9 os_prio=31 tid=0x00007feedd002800 nid=0x4b03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread2" #7 daemon prio=9 os_prio=31 tid=0x00007feedd002000 nid=0x4903 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=31 tid=0x00007feedd001000 nid=0x4703 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=31 tid=0x00007feedb053000 nid=0x4503 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 tid=0x00007feedb060000 nid=0x3c0f waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=31 tid=0x00007feedb838800 nid=0x3503 in Object.wait() [0x0000000121a73000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:142)
        - locked <0x00000006c0256560> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:158)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=31 tid=0x00007feedc004000 nid=0x3303 in Object.wait() [0x0000000121970000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)
        - locked <0x00000006c0256778> (a java.lang.ref.Reference$Lock)

"main" #1 prio=5 os_prio=31 tid=0x00007feed9800800 nid=0x1303 waiting on condition [0x0000000103f1e000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000006c02569b8> (a java.util.concurrent.CountDownLatch$Sync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedIntery(AbstractQueuedSynchronizer.java:1304)
        at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
        at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:175)
        at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:118)
        at javafx.application.Application.launch(Application.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1461)
        at org.codehaus.groovy.runtime.callsite.StaticMetaClassSite.callStatic(StaticMetaClassSite.java:62)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:157)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:169)
        at com.jhegg.github.notifier.App.main(App.groovy:36)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:363)
        at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:303)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
 at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)

"VM Thread" os_prio=31 tid=0x00007feedb838000 nid=0x3103 runnable

"GC task thread#0 (ParallelGC)" os_prio=31 tid=0x00007feedb004800 nid=0x2103 runnable

"GC task thread#1 (ParallelGC)" os_prio=31 tid=0x00007feedb005000 nid=0x2303 runnable

"GC task thread#2 (ParallelGC)" os_prio=31 tid=0x00007feedb005800 nid=0x2503 runnable

"GC task thread#3 (ParallelGC)" os_prio=31 tid=0x00007feedb006000 nid=0x2703 runnable

"GC task thread#4 (ParallelGC)" os_prio=31 tid=0x00007feedb007000 nid=0x2903 runnable

"GC task thread#5 (ParallelGC)" os_prio=31 tid=0x00007feedb007800 nid=0x2b03 runnable

"GC task thread#6 (ParallelGC)" os_prio=31 tid=0x00007feedb008000 nid=0x2d03 runnable

"GC task thread#7 (ParallelGC)" os_prio=31 tid=0x00007feedb008800 nid=0x2f03 runnable

"VM Periodic Task Thread" os_prio=31 tid=0x00007feedb054800 nid=0x4f03 waiting on condition

JNI global references: 1130

Heap
 PSYoungGen      total 91648K, used 44491K [0x000000076ab00000, 0x0000000771200000, 0x00000007c0000000)
  eden space 80896K, 54% used [0x000000076ab00000,0x000000076d672d20,0x000000076fa00000)
  from space 10752K, 0% used [0x0000000770780000,0x0000000770780000,0x0000000771200000)
  to   space 10752K, 0% used [0x000000076fd00000,0x000000076fd00000,0x0000000770780000)
 ParOldGen       total 214528K, used 24817K [0x00000006c0000000, 0x00000006cd180000, 0x000000076ab00000)
  object space 214528K, 11% used [0x00000006c0000000,0x00000006c183c6c0,0x00000006cd180000)
 Metaspace       used 35212K, capacity 37030K, committed 37168K, reserved 1081344K
  class space    used 4853K, capacity 5297K, committed 5424K, reserved 1048576K
```

**Comment by jhegg** [comment]
@whodevil This should now be resolved, let me know if it shows up again.

**Comment by whodevil** [comment]
Oh cook, I'm just now seeing this.
